export const LV_LIST = [
  {
    modul_id: "1.1",
    modul_titel: "Propädeutik",
    lectures: [
      "Wissenschaftliches Arbeiten, Methoden und Strategien des Lernens",
      "Informationstechnologien in der Sozialen Arbeit",
    ],
  },
  {
    modul_id: "1.2",
    modul_titel: "Einführung in die Wissenschaft der Sozialen Arbeit",
    lectures: ["Geschichte der Sozialen Arbeit", "Einführung in die Theorien der Sozialen Arbeit"],
  },
  { modul_id: "1.3", modul_titel: "OTIS/Sozialwirtschaft", lectures: ["OTIS", "Sozialwirtschaft"] },
  { modul_id: "1.4", modul_titel: "Wissenschaft der Sozialen Arbeit", lectures: ["Theorien der Sozialen Arbeit"] },
  { modul_id: "1.5", modul_titel: "Forschungsmethoden", lectures: ["Forschungsmethoden"] },
  {
    modul_id: "1.6",
    modul_titel: "Soziologische Grundlagen",
    lectures: ["Ringvorlesung Soziologische Grundlagen", "Seminar Soziologische Grundlagen"],
  },
  {
    modul_id: "1.7",
    modul_titel: "Psychologische Grundlagen",
    lectures: ["Psychologische Grundlagen"],
  },
  {
    modul_id: "1.8",
    modul_titel: "Pädagogische Grundlagen",
    lectures: ["Ringvorlesung Pädagogische Grundlagen", "Seminar Pädagogische Grundlagen"],
  },
  {
    modul_id: "1.9",
    modul_titel: "Politikwissenschaftliche Grundlagen",
    lectures: ["Ringvorlesung Politische Bildung", "Seminar Politik und Sozialpolitik"],
  },
  { modul_id: "1.10", modul_titel: "Medizinische Grundlagen", lectures: ["Medizinische Grundlagen"] },
  {
    modul_id: "1.11",
    modul_titel: "Rechtsgrundlagen Sozialer Arbeit, Sozialrecht",
    lectures: ["Rechtsgrundlagen Sozialer Arbeit", "Sozialrecht"],
  },
  {
    modul_id: "1.12",
    modul_titel: "Familien-, Kinder- und Jugendhilferecht",
    lectures: ["Familienrecht", "Kinder- und Jugendhilferecht"],
  },
  {
    modul_id: "1.13",
    modul_titel: "Entwicklung, Erziehung und Bildung",
    lectures: ["Entwicklung, Erziehung und Bildung"],
  },
  {
    modul_id: "1.14",
    modul_titel: "Gesundheit und Krankheit",
    lectures: ["Gesundheit und Krankheit"],
  },
  {
    modul_id: "1.15",
    modul_titel: "Soziale Ungleichheit / Armut",
    lectures: ["Ringvorlesung", "Projektbetreuung"],
  },
  { modul_id: "1.16", modul_titel: "Ethik in der Sozialen Arbeit", lectures: ["Ethik in der Sozialen Arbeit"] },
  {
    modul_id: "2.1",
    modul_titel: "Kultur, Ästhetik, Bewegung (Praxisangebot)",
    lectures: [],
  },
  {
    modul_id: "2.1.",
    modul_titel: "Kultur, Ästhetik, Bewegung (Ringvorlesung)",
    lectures: ["Ringvorlesung Kultur, Ästhetik und Bewegung"],
  },
  {
    modul_id: "2.2",
    modul_titel: "Gesprächsführung und Beobachtung, Präsentation und Moderation",
    lectures: ["Gesprächsführung und Beobachtung", "Präsentation und Moderation"],
  },
  {
    modul_id: "2.3",
    modul_titel: "Arbeit mit Einzelnen und Familien",
    lectures: ["Arbeit mit Familien und Einzelnen"],
  },
  { modul_id: 20, modul_titel: "Arbeit mit Gruppen", lectures: ["Arbeit mit Gruppen"] },
  {
    modul_id: "2.5",
    modul_titel: "Gemeinwesenarbeit",
    lectures: ["Gemeinwesenarbeit"],
  },
  {
    modul_id: "3.3",
    modul_titel: "PTT-Seminar",
    lectures: [],
  },
  {
    modul_id: "4.2.1",
    modul_titel: "Querschnitt: Abweichendes Verhalten und soziale Kontrolle",
    lectures: ["Querschnitt: Abweichendes Verhalten und soziale Kontrolle"],
  },
  {
    modul_id: "4.2.2",
    modul_titel: "Querschnitt: Soziale Arbeit mit und für ältere Menschen",
    lectures: ["Querschnitt: Soziale Arbeit mit und für ältere Menschen"],
  },
  {
    modul_id: "4.2.3",
    modul_titel: "Querschnitt: Geschlechtssensible Konzepte",
    lectures: ["Querschnitt: Geschlechtssensible Konzepte"],
  },
  {
    modul_id: "4.2.4",
    modul_titel: "Querschnitt: Praktische Erlebnispädagogik",
    lectures: [],
  },
  {
    modul_id: "4.2.5",
    modul_titel: "Querschnitt: Kulturelle Diversität",
    lectures: ["Querschnitt: Kulturelle Diversität"],
  },
  {
    modul_id: "4.2.6",
    modul_titel: "Querschnitt: Internationale Soziale Arbeit",
    lectures: ["Querschnitt: Internationale Soziale Arbeit"],
  },
  {
    modul_id: "4.2.7",
    modul_titel: "Querschnitt: Medien in der Sozialen Arbeit",
    lectures: ["Querschnitt: Medien in der Sozialen Arbeit"],
  },
  {
    modul_id: "4.2.8",
    modul_titel: "Querschnitt: Sozial- und Jugendhilfeplanung, Organisation Sozialer Dienste",
    lectures: ["Querschnitt: Sozial- und Jugendhilfeplanung, Organisation Sozialer Dienste"],
  },
  {
    modul_id: "4.2.9",
    modul_titel: "Querschnitt: Digitale Soziale Arbeit/ Soziale Arbeit im virtuellen Raum",
    lectures: ["Querschnitt: Digitale Soziale Arbeit/ Soziale Arbeit im virtuellen Raum"],
  },
  {
    modul_id: "4.2.10",
    modul_titel: "Querschnitt: Grundlagen des Sozialmanagements",
    lectures: ["Querschnitt: Grundlagen des Sozialmanagements"],
  },
  {
    modul_id: "4.2.11",
    modul_titel: "Querschnitt: Onlineberatung",
    lectures: ["Querschnitt: Onlineberatung"],
  },
  {
    modul_id: "4.2.12",
    modul_titel: "Querschnitt: Soziale Arbeit und Menschenrechte",
    lectures: ["Querschnitt: Soziale Arbeit und Menschenrechte"],
  },
  {
    modul_id: "4.2.13",
    modul_titel: "Querschnitt: Kulturelle Bildung in der Sozialen Arbeit",
    lectures: ["Querschnitt: Kulturelle Bildung in der Sozialen Arbeit"],
  },
  {
    modul_id: "4.2.14",
    modul_titel: "Querschnitt: Psychische Belastungen und Störungen - Schwerpunkt Kinder und Jugendliche",
    lectures: ["Querschnitt: Psychische Belastungen und Störungen - Schwerpunkt Kinder und Jugendliche"],
  },
  {
    modul_id: "4.2.15",
    modul_titel: "Querschnitt: Psychische Belastungen und Störungen - Schwerpunkt Erwachsene",
    lectures: ["Querschnitt: Psychische Belastungen und Störungen - Schwerpunkt Erwachsene"],
  },
  {
    modul_id: "4.2.16",
    modul_titel: "Querschnitt: Freiwilligenmanagement",
    lectures: ["Querschnitt: Freiwilligenmanagement"],
  },
  {
    modul_id: "4.2.17",
    modul_titel: "Querschnitt: Forschung in der Sozialen Arbeit",
    lectures: ["Querschnitt: Forschung in der Sozialen Arbeit"],
  },
  {
    modul_id: "4.2.18",
    modul_titel: "Querschnitt: StadtraumGesellschaft",
    lectures: ["Querschnitt: StadtraumGesellschaft"],
  },
  {
    modul_id: "4.4",
    modul_titel: "Allgemeinwissenschaftliche/ Fachbezogene Wahlpflichtfächer",
    lectures: [],
  },
];

export const SEMESTER = [
  { value: "SS", label: "Sommersemester" },
  { value: "WS", label: "Wintersemester" },
];

export const WEEKDAY = [
  { value: "0", label: "Montag" },
  { value: "1", label: "Dienstag" },
  { value: "2", label: "Mittwoch" },
  { value: "3", label: "Donnerstag" },
  { value: "4", label: "Freitag" },
  { value: "5", label: "Samstag" },
];

export const LV_RHYTHMUS = [
  { value: "W", label: "wöchentlich" },
  { value: "WZ", label: "wöchentlich mit Zusatzterminen" },
  {
    value: "VZ2",
    label: "wöchentlich, doppelte SWS-Zahl, aber mit halbierter Anzahl Termine",
  },
  {
    value: "VZ",
    label: "vierzehntägig, dafür LV mit doppelter SWS-Zahl",
  },

  { value: "BK", label: "Blockveranstaltung" },
];

export const TIME_PICKER_VON = [
  { value: "08:00", label: "08:00" },
  { value: "08:45", label: "08:45" },
  { value: "09:45", label: "09:45" },
  { value: "10:30", label: "10:30" },
  { value: "11:30", label: "11:30" },
  { value: "12:15", label: "12:15" },
  { value: "14:00", label: "14:00" },
  { value: "14:45", label: "14:45" },
  { value: "15:45", label: "15:45" },
  { value: "16:30", label: "16:30" },
  { value: "17:30", label: "17:30" },
  { value: "18:15", label: "18:15" },
  { value: "19:15", label: "19:15" },
  { value: "20:00", label: "20:00" },
];

export const TIME_PICKER_BIS = [
  { value: "08:45", label: "08:45" },
  { value: "09:30", label: "09:30" },
  { value: "10:30", label: "10:30" },
  { value: "11:15", label: "11:15" },
  { value: "12:15", label: "12:15" },
  { value: "13:00", label: "13:00" },
  { value: "14:45", label: "14:45" },
  { value: "15:30", label: "15:30" },
  { value: "16:30", label: "16:30" },
  { value: "17:15", label: "17:15" },
  { value: "18:15", label: "18:15" },
  { value: "19:00", label: "19:00" },
  { value: "20:00", label: "20:00" },
  { value: "20:45", label: "20:45" },
];

export const VIRTUELLES_FORMAT = [
  { value: "Präsenz", label: "Präsenz" },
  { value: "Hybrid (synchron)", label: "Hybrid (synchron)" },
  { value: "Hybrid (asynchron)", label: "Hybrid (asynchron)" },
  { value: "Reine Onlineveranstaltung", label: "Reine Onlineveranstaltung" },
];

export const DUMMY_TABLE_DATA = [
  {
    id: "1",
    name: "Lehner",
    vorname: "Dietmar",
    semester: "",
    modul_titel: "1.3 OTIS/Sozialwirtschaft",
    lv_titel: "OTIS",
    block_titel: "",
    rhythmus: "wöchentlich",
    vformat: "Präsenz",
    lv_termin: "Montag, 10:30-14:45",
    start_datum: "",
    raum_wunsch: "",
    co_dozent: "",
    max_tn: "",
    warteliste_len: "",
    status: "storniert",
    rawData: {
      id: "4",
      benutzer_id: "806",
      modul_id: "1.2",
      modul_titel: "Einführung in die Wissenschaft der Sozialen Arbeit",
      lv_id: "3",
      lv_titel: "Geschichte der Sozialen Arbeit",
      lv_frei_titel: null,
      block_titel: null,
      start_datum: null,
      wochentag: "0",
      anfangszeit: "10:00",
      dauer: "90",
      dozent: "Testsw, Dozent",
      rhythmus: "W",
      co_dozent: null,
      max_tn: null,
      warteliste_len: null,
      raum_wunsch: null,
      vformat: "Präsenz",
      anmerkung: null,
      status: "geplant",
    },
  },
  {
    id: "2",
    name: "Lehner",
    vorname: "Dietmar",
    semester: "",
    modul_titel: "1.3 OTIS/Sozialwirtschaft",
    lv_titel: "OTIS",
    block_titel: "",
    rhythmus: "wöchentlich",
    vformat: "Präsenz",
    lv_termin: "Montag, 10:30-14:45",
    start_datum: "",
    raum_wunsch: "",
    co_dozent: "",
    max_tn: "",
    warteliste_len: "",
    status: "geplant",
    rawData: {
      id: "4",
      benutzer_id: "806",
      modul_id: "1.2",
      modul_titel: "Einführung in die Wissenschaft der Sozialen Arbeit",
      lv_id: "3",
      lv_titel: "Geschichte der Sozialen Arbeit",
      lv_frei_titel: null,
      block_titel: null,
      start_datum: null,
      wochentag: "0",
      anfangszeit: "10:00",
      dauer: "90",
      dozent: "Testsw, Dozent",
      rhythmus: "W",
      co_dozent: null,
      max_tn: null,
      warteliste_len: null,
      raum_wunsch: null,
      vformat: "Präsenz",
      anmerkung: null,
      status: "geplant",
    },
  },
  {
    id: "3",
    name: "Lehner",
    vorname: "Dietmar",
    semester: "",
    modul_titel: "1.3 OTIS/Sozialwirtschaft",
    lv_titel: "OTIS",
    block_titel: "",
    rhythmus: "wöchentlich",
    vformat: "Präsenz",
    lv_termin: "Montag, 10:30-14:45",
    start_datum: "",
    raum_wunsch: "",
    co_dozent: "",
    max_tn: "",
    warteliste_len: "",
    status: "angefragt",
    rawData: {
      id: "4",
      benutzer_id: "806",
      modul_id: "1.2",
      modul_titel: "Einführung in die Wissenschaft der Sozialen Arbeit",
      lv_id: "3",
      lv_titel: "Geschichte der Sozialen Arbeit",
      lv_frei_titel: null,
      block_titel: null,
      start_datum: null,
      wochentag: "0",
      anfangszeit: "10:00",
      dauer: "90",
      dozent: "Testsw, Dozent",
      rhythmus: "W",
      co_dozent: null,
      max_tn: null,
      warteliste_len: null,
      raum_wunsch: null,
      vformat: "Präsenz",
      anmerkung: null,
      status: "geplant",
    },
  },
];

export const exampleTermin = {
  id: "bc9b86b0-06bb-59b1-854e-ebe60865ec1b",
  name: "Testsw",
  vorname: "Dozent",
  datum: "",
  block_titel: "",
  semester: "",
  modul_id: "1.1",
  modul_titel: "Propädeutik",
  lv_titel: "Wissenschaftliches Arbeiten, Methoden und Strategien des Lernens",
  co_dozent: "",
  rhythmus: "wöchentlich",
  vformat: ["Präsenz"],
  anmerkungen: "",
  max_tn: "",
  warteliste_len: "",
  raum_wunsch: "",
  start_datum: "",
  wochentag: "0",
  von: "08:00",
  bis: "10:30",
};
